version: "3.8"

services:
  esm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ESM-container
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    tty: true
